### ISSUE TITLE
Message parsing not being rebuilt after using Control (^) D

### ISSUE THREAD

**Issue by qduong42** [artur01-code/ft_irc#31]
Description: US + ^D + ER 1 2 3 4 doesnt rebuilt USER command.
Expected behavior: USER command should be rebuilt and triggered.
Suspected affected functions/Class: Message parse function

**Comment by artur01-code** [comment]
When you press CTRL + D it counts as one command. That means {NA + CTRL&D + MES} gets passed as cmd[0] = NA and cmd[1] = MAES.
Possible solution:
when the checkcommands() function couldn't find a match then return 1. When at least two times in a row a 1 got returned try to build the strings together and pass them as a new cmd.
