### ISSUE TITLE
You can not reregister throws falsely (on MAIN branch!)

### ISSUE THREAD

**Issue by Luxins** [artur01-code/ft_irc#52]
USER a b c d
NICK A
:default 375 A :- default Message of the day - 
:default 372 A :default
:default 376 A :End of /MOTD command.
(YOU HAVE TO GIVE A NEWLINE HERE)
:default 462 A :You may not reregister
:default 433 A A :Nickname is already in use

**Comment by artur01-code** [comment]
In the way you describe the error, I don't get an error! 
Please clarify how to reproduce the error!
