### ISSUE TITLE
INVITE bug

### ISSUE THREAD

**Issue by Luxins** [artur01-code/ft_irc#71]
Description: Setting a channel to invite only via adium works. But you can't even join when beeing invited into the invite only.
Expected behaviour: Invited client can join an invite only server
Steps to reproduce:

1. Open Adium
2. Make channel
3. Set MODE <channel> +i
4. TRY TO JOIN WITH THE UNINVITED <other client>!
5. INVITE <other client> <channel> 
6. Try to Join channel with <other client>

INVITE cmd or INVITERPLY

**Comment by artur01-code** [comment]
I think you mixed up the syntax and I did as well. 
The commands that you need to use are:

/MODE <channel> +i                         --> then the channel is invite only
/INVITE <nickname> <channel>      --> invites someone

I always tried the invite command with the channel first and then the nickname which is of course not working
