### ISSUE TITLE
WHO issue

### ISSUE THREAD

**Issue by Luxins** [artur01-code/ft_irc#75]
Description: Who command does not work in Adium
Steps to reproduce:

1.  Open a channel
2. Join with a second user
3. Execute '/WHO *'

NOTE: WHOREPLY and ENDOFWHO are identical to Konstantins replies. They also have this command not working.
I highly suspect that it is a norm error in the replies, because the replies are indeed send.
It would be good to consult another irc as reference.

**Comment by artur01-code** [comment]
The Replies are correct for sure so we can only assume that the problem is on adiums side
